

networks:
  agent-network:
    driver: bridge

services:
  browser-agent:
    build:
      context: ./services/browser-agent
    networks:
      - agent-network
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./logs:/home/agentuser
    # Port 5900 is for VNC, exposed only to the internal network

  backend:
    build:
      context: ./services/backend
    ports:
      - "8000:8000"
    networks:
      - agent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./services/frontend
    ports:
      - "8080:80"
    networks:
      - agent-network
    depends_on:
      - backend
      - guacamole

  guacd:
    image: guacamole/guacd
    networks:
      - agent-network
    restart: always

  guacamole:
    image: guacamole/guacamole
    ports:
      - "8081:8080"
    networks:
      - agent-network
    depends_on:
      - guacd
    environment:
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOME: /etc/guacamole
    volumes:
      - ./infra/guacamole:/etc/guacamole
    restart: always
