
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "xagent-cloud-run-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.2"
  project_id                    = var.xagent_cloud_run_service_project_id
  location                      = var.cloud_run_location
  service_name                  = "xagent-service"
  containers                    = [{ container_image = var.container_image, container_name = "xagent-container" }]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/aiplatform.user"]

  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 1
  }
  service_labels = {
    xagent_vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  members = ["allUsers"]
}
module "xagent-vertex-ai" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = var.xagent_vertex_ai_project_id
  activate_apis = ["aiplatform.googleapis.com"]
}
module "xagent-global-lb-frontend" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v13.1.0"
  name          = "xagent-lb-frontend"
  project_id    = var.xagent_global_lb_frontend_project_id
  url_map_input = module.xagent-global-lb-backend.backend_service_info
}
module "xagent-global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.1.0"
  name       = "xagent-lb-backend"
  project_id = var.xagent_global_lb_backend_project_id
  serverless_neg_backends = [{
    region          = module.xagent-cloud-run-service.location
    service_name    = module.xagent-cloud-run-service.service_name
    service_version = ""
    type            = "cloud-run"
  }]
}
# module "apphub" {
#   source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.3.0"
#   project_id     = var.apphub_project_id
#   location       = var.apphub_location
#   service_uris   = concat([module.xagent-cloud-run-service.apphub_service_uri], module.xagent-global-lb-frontend.apphub_service_uri, module.xagent-global-lb-backend.apphub_service_uri)
#   application_id = var.apphub_application_id
# }
