
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "xagent_cloud_run_service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "xagent_vertex_ai_project_id" {
  description = "The GCP project you want to enable APIs on"
  type = string
}
variable "xagent_global_lb_frontend_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type = string
}
variable "xagent_global_lb_backend_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type = string
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}

variable "container_image" {
  description = "The container image URI to deploy on Cloud Run (e.g., us-central1-docker.pkg.dev/PROJECT/REPO/xagent:TAG)"
  type        = string
}

variable "cloud_run_location" {
  description = "Region for Cloud Run service (e.g., us-east1)"
  type        = string
}
